# Generated by Django 4.2.6 on 2023-10-15 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pedido', models.PositiveIntegerField()),
                ('costo_envio', models.PositiveIntegerField()),
                ('tasa_aduana', models.PositiveIntegerField()),
                ('impuesto_iva', models.PositiveIntegerField()),
                ('total_agregado', models.PositiveIntegerField()),
                ('total_compra_clp', models.PositiveIntegerField()),
                ('total_compra_usd', models.PositiveIntegerField()),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
            ],
        ),
    ]
