# Generated by Django 4.2.6 on 2023-10-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unidades', models.PositiveIntegerField()),
                ('costo_unidad_dolar', models.PositiveIntegerField()),
                ('nombre_articulo', models.CharField(max_length=250)),
                ('codigo_articulo', models.PositiveIntegerField()),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('costo_envio', models.PositiveIntegerField()),
            ],
        ),
    ]
